### ISSUE TITLE
Import does not work

### ISSUE THREAD

**Issue by hollow1** [JPCERTCC/LogonTracer#1]
I hate to say it, but importing does not work not for github version nor for docker.
I see that DB is populated with my data, but the web interface does display any data uploaded.

**Comment by TheBigBear** [comment]
@shu-tom same for me, it does say import is successful but it only has the sample data in web ui to search.

I have mounted a local dir to container using the ```-v``` docker cmd and then attached to a interactive shell and deleted all records and then run an import and that worked. Not sure if this helps. Let me know if I should check something in the container before or after the web ui import that does not seem to load into the databases.

1 added the following to my start or the container
```-v ~/myeventlogs/:/tmp/myeventlogs``` 
2 attached myself to container on an interactive shell
```
docker exec -i -t 17a0aeb6d1b1 /bin/bash
```
3 removed existing data
``` 
cd /usr/local/src/LogonTracer/
python3 logontracer.py --delete
python3 logontracer.py -e /tmp/myeventlogs/myevents.evtx -z +9 -u neo4j -p password -s localhost
```

**Comment by jared703** [comment]
I'm also having an issue uploading new data with the docker version.

**Comment by Xyrodileas** [comment]
Same issue here. After uploading data, nothing show on the interface.

**Comment by wh1t3-n01s3** [comment]
Same issue. Using the docker image, uploading an evtx from a Win7 box doesn't have any data.

**Comment by shu-tom** [comment]
Fixed an issue that the upload status bar of the Web UI was not updated.

Web UI uses Javascript, please enable it.
If the EVTX file is large, it takes time to analyze it.
And, if parse process is running, the following bar will be displayed.
![upload_bar](https://user-images.githubusercontent.com/8147599/33542490-9fcf3f14-d916-11e7-8431-3f52dd49d019.png)

Docker image has also been updated.

**Comment by tatdatpham** [comment]
Sometime Parsing process over 100%, in my case, it up to 105% and after that, it show success in status bar and notthing ...
![image](https://user-images.githubusercontent.com/3429970/33601342-80bfdc5a-d9de-11e7-9a1c-b5da0593eb2b.png)

**Comment by shu-tom** [comment]
@tatdatpham After importing EVTX, you need to reload the web browser.

**Comment by jared703** [comment]
Hi @shu-tom. I've not been able to run the newest docker image successfully after pulling the newest build. With the previous build I was able to connect to the webserver per your documentation, but now it doesn't seem to work. Nothing else changed on my end except for pulling the newest docker image. Thank you for the support and efforts with this project.

**Comment by wh1t3-n01s3** [comment]
@jared703 Are you able to get the UI to load? I had that problem initially and after waiting for a minute or two (literally) and hitting refresh on the browser the UI loaded. Using Chromium on Ubuntu 16.04

**Comment by jared703** [comment]
@wh1t3-n01s3 I could before i pulled down the latest docker build, but after updating I can't get it to load at all. My setup was on OSX using Chrome.

**Comment by wh1t3-n01s3** [comment]
If you run netstat do you see port 8080 listening?  On the new docker image after pulling the new one I had to kill the docker container, restart it, then wait a couple minutes before I saw port 8080 listening.

**Comment by jared703** [comment]
@wh1t3-n01s3 seems to be working now. Had to take @hollow1's approach though.

**Comment by shu-tom** [comment]
@tatdatpham Fixed a bug where the parse status over 100%.

**Comment by shu-tom** [comment]
Fixed a issue that Web UI can not be used due to limitation of the number of simultaneous accesses of neo4j.
If you can not import the EXTX file, please add a new issue.

For information on how to import EVTX files, please refer to the following URL.
https://github.com/JPCERTCC/LogonTracer/wiki/How-to-Use
for Docker
https://github.com/JPCERTCC/LogonTracer/wiki/jump-start-with-docker
