### ISSUE TITLE
Other Windows Log Formats

### ISSUE THREAD

**Issue by seajaysec** [JPCERTCC/LogonTracer#10]
Would it be possible to add support for importing CSV and XML formatted Windows Event Logs? Often I come across systems that I'm able to remotely administer and export events for, but not in EVTX format.

**Comment by shu-tom** [comment]
Thank you for your request.
I will add a function to import other files.

**Comment by shu-tom** [comment]
Added a function to parse XML file for event log.
On the other hand, it is difficult to support CSV file because character codes are different based on code page of Windows OS.

**Comment by seajaysec** [comment]
That's ok, XML is perfect. Thank you!

**Comment by seajaysec** [comment]
Is the Docker image updated? If not I can figure that part out on my own.

**Comment by shu-tom** [comment]
The docker image has been updated. Please download the new version.
