### ISSUE TITLE
The event 4672: Assign special privileges is not parsed ?

### ISSUE THREAD

**Issue by belveruski** [JPCERTCC/LogonTracer#101]
- I don't see a filter for event **4672: Assign special privileges**:
![image](https://user-images.githubusercontent.com/38252603/106400939-b77c3100-6421-11eb-8705-681e20d2fdbc.png)
- I uploaded a `Security.evtx` file containing **4672** event but Logon Tracer didn't parsed it.

It's a bug or it's normal, can i get explanations ?
Thanks in advance

**Comment by t-tani** [comment]
Are there any red nodes on your graph after loading your event log? If so, 4672 have parsed correctly. Event ID 4672 is used to check if special privileges have been assigned to the user, and the node color shows it.
