### ISSUE TITLE
Questions - logs from Domain controllers only or all servers?

### ISSUE THREAD

**Issue by godstoge** [JPCERTCC/LogonTracer#105]
When you refer to the use of "Active Directory logs" - do you mean security.evtx from domain controllers _only_?
Or do you mean security.evtx from all domain-joined servers?

The reason I ask is because in IR engagements we often see Domain controller's security.evtx contains only a few hours of data due to log size limitations.

**Comment by shu-tom** [comment]
We are analyzing DC security.evtx. However, the login event log also record in the server, so you can analyze it with LogonTracer.
