### ISSUE TITLE
This event log did not include logs to be visualized. Please check the details of the event log.

### ISSUE THREAD

**Issue by esdk123** [JPCERTCC/LogonTracer#106]
Now loading 20300 records. [+] Now loading 20400 records. [+] Now loading 20500 records. [+] Now loading 20600 records. [+] Now loading 20700 records. [+] Now loading 20800 records. [+] Now loading 20900 records. [+] Now loading 21000 records. [+] Now loading 21100 records. [+] Now loading 21200 records. [+] Now loading 21300 records. [+] Now loading 21400 records. [+] Now loading 21500 records. [+] Now loading 21600 records. [+] Now loading 21700 records. [+] Now loading 21800 records. [+] Now loading 21900 records. [+] Now loading 22000 records. [+] Now loading 22100 records. [+] Now loading 22200 records. [+] Load finished. [+] Total Event log is 22220. [!] This event log did not include logs to be visualized. Please check the details of the event log.

 [!] This event log did not include logs to be visualized. Please check the details of the event log.

Why does this happen? My logs are exported from the server.

- [ ] 
![image](https://user-images.githubusercontent.com/58690750/110593543-aa87f580-81b6-11eb-8274-79f3270fca94.png)

- [ ]

**Comment by t-tani** [comment]
Did you upload the security log of your domain controller? If so, please check if your logs contain EventID 4624/4625. You could check it with the EventViewer, which is installed on Windows default.
Or if you had set your audit policy NOT to record the Account Logon Events, LogonTracer could not find logs required to visualize the graph.
