### ISSUE TITLE
Wiki(How to install): JDK8 is not supported by neo4j(ver 4) 

### ISSUE THREAD

**Issue by fukusuket** [JPCERTCC/LogonTracer#128]
Thank you so much for maitaing the excellent tool :)

When I installed  `neo4j(v4.4.15)` with `JDK8` [according to the wiki](https://github.com/JPCERTCC/LogonTracer/wiki/for-os-x), I got the following error.
```
fukusuke@fukusukenoAir bin % java -version
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.352-b08, mixed mode)
fukusuke@fukusukenoAir bin % ./neo4j help
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/neo4j/server/startup/Neo4jCommand has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
...
```
After searching, it seems that `neo4j(v4)` doesn't support `JDK8`.(only `neo4j(v3)` support `JDK8`)
 - [System requirements(neo4j manual)](https://neo4j.com/docs/operations-manual/4.4/installation/requirements/#deployment-requirements-java)

Could you change the following parts of the installation manual from `JDK8` to `JDK11`?(or specify `neo4j` version)
- https://github.com/JPCERTCC/LogonTracer/wiki/for-linux#install-packages
- https://github.com/JPCERTCC/LogonTracer/wiki/for-os-x#install-packages

(I confirmed that I can run `neo4j` and `LogonTracer` on `JDK11`)

I would appreciate it if you could confirm it🙏
Regards.

**Comment by shu-tom** [comment]
Thank you for your good issue. We will be updating the Wiki next week.

**Comment by fukusuket** [comment]
Thank you so much for comment and maintaining the wiki and tools :)

**Comment by shu-tom** [comment]
I have updated the wiki.
https://github.com/JPCERTCC/LogonTracer/wiki/for-linux
