### ISSUE TITLE
Freeze screen on import evtx

### ISSUE THREAD

**Issue by giacomoconti1978** [JPCERTCC/LogonTracer#135]
Hi, i recently install LogonTracer on Ubuntu 22.04 with Neo4j enterprice. I have a problem when load Security.evtx from web gui (also from termital). I attach log:
[+] Script start. 2023/04/05 06:31:00
[+] Neo4j Kernel 5.6.0 (Enterprise)
[+] Time zone is 1.
[+] Last record number is 62031.
[+] Start parsing the EVTX file.
[+] Parse the EVTX file sample/Security.evtx.
[+] Now loading 2500 records.Traceback (most recent call last):
  File "/LogonTracer/logontracer.py", line 2883, in <module>
    main()
  File "/LogonTracer/logontracer.py", line 2867, in main
    parse_evtx(args.evtx, case)
  File "/LogonTracer/logontracer.py", line 1962, in parse_evtx
    event_set = event_set.append(event_series, ignore_index=True)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

And Parsing freeze in web gui
Any idea?
Thanks

**Comment by shu-tom** [comment]
This isssue has been fixed.
