### ISSUE TITLE
Error Upload event.

### ISSUE THREAD

**Issue by Pablo1816** [JPCERTCC/LogonTracer#14]
Hello, error upload event.evtx

#python3 logontracer.py -e /home/logon/Desktop/Security.evtx -z -3  -u neo4j -p password -s localhost
/home/logon/.local/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
[*] Script start. 2018/04/24 17:28:42
[*] Time zone is -3.
[*] Last record number is 49147872.
[*] Start parsing the EVTX file.
[*] Parse the EVTX file /home/logon/Desktop/Security.evtx.
[*] Now loading 242200 records.  
[*] Load finished.
[*] Total Event log is 242213.
[*] Calculate PageRank.
[*] Calculate ChangeFinder.
Traceback (most recent call last):
  File "logontracer.py", line 656, in <module>
    main()
  File "logontracer.py", line 645, in main
    parse_evtx(args.evtx, GRAPH)
  File "logontracer.py", line 552, in parse_evtx
    timelines, detects = adetection(count_set, username_set, ranks, starttime, tohours)
  File "logontracer.py", line 233, in adetection
    u = ranks[users[num]]
KeyError: 'hmemez'

**Comment by shu-tom** [comment]
@Pablo1816 Can you share the event log to me in order to resolve this issue?

**Comment by RadfordDA** [comment]
I get the same issue

] Now loading 395200 records.[
[*] Load finished.
[*] Total Event log is 395219.
[*] Calculate PageRank.
[*] Calculate ChangeFinder.
Traceback (most recent call last):
  File "./logontracer.py", line 693, in <module>
    main()
  File "./logontracer.py", line 682, in main
    parse_evtx(args.evtx, GRAPH)
  File "./logontracer.py", line 580, in parse_evtx
    timelines, detects = adetection(count_set, username_set, ranks, starttime, tohours)
  File "./logontracer.py", line 233, in adetection
    u = ranks[users[num]]
KeyError: 'server'

**Comment by Pablo1816** [comment]
Attached I send the log security

[Security.zip](https://github.com/JPCERTCC/LogonTracer/files/1968697/Security.zip)

**Comment by shu-tom** [comment]
@Pablo1816 Thank you for sharing the Event log. I found that this issue occurs because the same name is used for the account name and host name.
I will fix this issue.

**Comment by shu-tom** [comment]
Fixed a bug. Please try the fixed version.

**Comment by Pablo1816** [comment]
Thank you very much worked......, a query as I delete previously loaded events?

**Comment by shu-tom** [comment]
@Pablo1816 You can delete it using option --delete.

**Comment by Pablo1816** [comment]
@shu-tom  thank you..
