### ISSUE TITLE
unpack_from requires a buffer of at least 2 bytes

### ISSUE THREAD

**Issue by Pablo1816** [JPCERTCC/LogonTracer#15]
Hello, 
#python3 logontracer.py -e /home/logon/Downloads/Security3.evtx -z 3 -u neo4j -p password-s localhost
/home/logon/.local/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
[*] Script start. 2018/05/15 11:35:05
[*] Time zone is  3.
[*] Last record number is 5169506801.
[*] Start parsing the EVTX file.
[*] Parse the EVTX file /home/logon/Downloads/Security3.evtx.
[*] Now loading 25200 records.Traceback (most recent call last):
  File "/home/logon/.local/lib/python3.5/site-packages/Evtx/BinaryParser.py", line 302, in unpack_word
    return struct.unpack_from("<H", self._buf, o)[0]
struct.error: unpack_from requires a buffer of at least 2 bytes

**Comment by shu-tom** [comment]
This is an error output by python-evtx. The last record number of your uploaded EVTX file is very large. This file may be corrupted.
Would you export the EVTX file from Event Viewer and import it to LogonTracer again?
