### ISSUE TITLE
Pandas FutureWarning??

### ISSUE THREAD

**Issue by BBBruceYang** [JPCERTCC/LogonTracer#17]
Hello
When I upload a event log, it show me "waiting" and then stuck.
So I checked the log and found following   info.
```
/usr/local/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. 
Please use the pandas.tseries module instead. from pandas.core import datetools usage: logontracer.py [-h] [-r] [-o PORT] [-s SERVER] [-u USERNAME] [-p PASSWORD] [-e [EVTX [EVTX ...]]] [-x [XML [XML ...]]] [-z UTC] [-f DATE] [-t DATE] [--delete] logontracer.py: error: argument -z/--timezone: invalid int value: 'Time'
```

How do I fixed it?  Thx.

**Comment by shu-tom** [comment]
This is a known warning message does not affect the operation of LogonTracer.

I found the following error message.
``
logontracer.py: error: argument -z/--timezone: invalid int value: 'Time'
``
Did you set timezone when uploading EVTX file?

**Comment by BBBruceYang** [comment]
It worked!
I forgot to set timezone.
Thank you very much.
