### ISSUE TITLE
Event log Importing success - But nothing is displayed on screen

### ISSUE THREAD

**Issue by sahar55** [JPCERTCC/LogonTracer#18]
Hi guys, 
I've setup the environment using the docker image, everything works well with the sample that was provided.
I've attempted uploading my own event log and the upload&parsing was successful according to the log yet nothing was displayed in the page after the page refresh. 

> `[*] Script start. 2018/05/31 08:02:44 [*] Delete all nodes and relationships from this Neo4j database. [*] Time zone is 2. [*] Last record number is 558790. [*] Start parsing the EVTX file. [*] Parse the EVTX file Security.evtx. [*] Now loading 100 records. [*] Now loading 200 records. [*] Now loading 300 records. [*] Now loading 400 records. [*] Now loading 500 records. [*] Now loading 600 records. [*] Now loading 700 records. [*] Now loading 800 records. [*] Now loading 900 records. [*] Now loading 1000 records. [*] Now loading 1100 records. [*] Now loading 1200 records. [*] Now loading 1300 records. [*] Now loading 1400 records. [*] Now loading 1500 records. [*] Now loading 1600 records. [*] Now loading 1700 records. [*] Now loading 1800 records. [*] Now loading 1900 records. [*] Now loading 2000 records. [*] Now loading 2100 records. [*] Now loading 2200 records. [*] Now loading 2300 records. [*] Now loading 2400 records. [*] Now loading 2500 records. [*] Now loading 2600 records. [*] Now loading 2700 records. [*] Now loading 2800 records. [*] Now loading 2900 records. [*] Now loading 3000 records. [*] Now loading 3100 records. [*] Now loading 3200 records. [*] Now loading 3300 records. [*] Now loading 3400 records. [*] Now loading 3500 records. [*] Now loading 3600 records. [*] Now loading 3700 records. [*] Now loading 3800 records. [*] Now loading 3900 records. [*] Now loading 4000 records. [*] Now loading 4100 records. [*] Now loading 4200 records. [*] Now loading 4300 records. [*] Now loading 4400 records. [*] Now loading 4500 records. [*] Now loading 4600 records. [*] Now loading 4700 records. [*] Now loading 4800 records. [*] Now loading 4900 records. [*] Now loading 5000 records. [*] Now loading 5100 records. [*] Now loading 5200 records. [*] Now loading 5300 records. [*] Now loading 5400 records. [*] Now loading 5500 records. [*] Now loading 5600 records. [*] Now loading 5700 records. [*] Now loading 5800 records. [*] Now loading 5900 records. [*] Now loading 6000 records. [*] Now loading 6100 records. [*] Now loading 6200 records. [*] Now loading 6300 records. [*] Now loading 6400 records. [*] Now loading 6500 records. [*] Now loading 6600 records. [*] Now loading 6700 records. [*] Now loading 6800 records. [*] Now loading 6900 records. [*] Now loading 7000 records. [*] Now loading 7100 records. [*] Now loading 7200 records. [*] Now loading 7300 records. [*] Now loading 7400 records. [*] Now loading 7500 records. [*] Now loading 7600 records. [*] Now loading 7700 records. [*] Now loading 7800 records. [*] Now loading 7900 records. [*] Now loading 8000 records. [*] Now loading 8100 records. [*] Now loading 8200 records. [*] Now loading 8300 records. [*] Now loading 8400 records. [*] Now loading 8500 records. [*] Now loading 8600 records. [*] Now loading 8700 records. [*] Now loading 8800 records. [*] Now loading 8900 records. [*] Now loading 9000 records. [*] Now loading 9100 records. [*] Now loading 9200 records. [*] Now loading 9300 records. [*] Now loading 9400 records. [*] Now loading 9500 records. [*] Now loading 9600 records. [*] Now loading 9700 records. [*] Now loading 9800 records. [*] Now loading 9900 records. [*] Now loading 10000 records. [*] Now loading 10100 records. [*] Now loading 10200 records. [*] Now loading 10300 records. [*] Now loading 10400 records. [*] Now loading 10500 records. [*] Now loading 10600 records. [*] Now loading 10700 records. [*] Now loading 10800 records. [*] Now loading 10900 records. [*] Now loading 11000 records. [*] Now loading 11100 records. [*] Now loading 11200 records. [*] Now loading 11300 records. [*] Now loading 11400 records. [*] Now loading 11500 records. [*] Now loading 11600 records. [*] Now loading 11700 records. [*] Now loading 11800 records. [*] Now loading 11900 records. [*] Now loading 12000 records. [*] Now loading 12100 records. [*] Now loading 12200 records. [*] Now loading 12300 records. [*] Now loading 12400 records. [*] Now loading 12500 records. [*] Now loading 12600 records. [*] Now loading 12700 records. [*] Now loading 12800 records. [*] Now loading 12900 records. [*] Now loading 13000 records. [*] Now loading 13100 records. [*] Now loading 13200 records. [*] Now loading 13300 records. [*] Now loading 13400 records. [*] Now loading 13500 records. [*] Now loading 13600 records. [*] Now loading 13700 records. [*] Now loading 13800 records. [*] Now loading 13900 records. [*] Now loading 14000 records. [*] Now loading 14100 records. [*] Now loading 14200 records. [*] Now loading 14300 records. [*] Now loading 14400 records. [*] Now loading 14500 records. [*] Now loading 14600 records. [*] Now loading 14700 records. [*] Now loading 14800 records. [*] Now loading 14900 records. [*] Now loading 15000 records. [*] Now loading 15100 records. [*] Now loading 15200 records. [*] Now loading 15300 records. [*] Now loading 15400 records. [*] Now loading 15500 records. [*] Now loading 15600 records. [*] Now loading 15700 records. [*] Now loading 15800 records. [*] Now loading 15900 records. [*] Now loading 16000 records. [*] Now loading 16100 records. [*] Now loading 16200 records. [*] Now loading 16300 records. [*] Now loading 16400 records. [*] Now loading 16500 records. [*] Now loading 16600 records. [*] Now loading 16700 records. [*] Now loading 16800 records. [*] Now loading 16900 records. [*] Now loading 17000 records. [*] Now loading 17100 records. [*] Now loading 17200 records. [*] Now loading 17300 records. [*] Now loading 17400 records. [*] Now loading 17500 records. [*] Now loading 17600 records. [*] Now loading 17700 records. [*] Now loading 17800 records. [*] Now loading 17900 records. [*] Now loading 18000 records. [*] Now loading 18100 records. [*] Now loading 18200 records. [*] Now loading 18300 records. [*] Now loading 18400 records. [*] Now loading 18500 records. [*] Now loading 18600 records. [*] Now loading 18700 records. [*] Now loading 18800 records. [*] Now loading 18900 records. [*] Now loading 19000 records. [*] Now loading 19100 records. [*] Now loading 19200 records. [*] Now loading 19300 records. [*] Now loading 19400 records. [*] Now loading 19500 records. [*] Now loading 19600 records. [*] Now loading 19700 records. [*] Now loading 19800 records. [*] Now loading 19900 records. [*] Now loading 20000 records. [*] Now loading 20100 records. [*] Now loading 20200 records. [*] Now loading 20300 records. [*] Now loading 20400 records. [*] Now loading 20500 records. [*] Now loading 20600 records. [*] Now loading 20700 records. [*] Now loading 20800 records. [*] Now loading 20900 records. [*] Now loading 21000 records. [*] Now loading 21100 records. [*] Now loading 21200 records. [*] Now loading 21300 records. [*] Now loading 21400 records. [*] Now loading 21500 records. [*] Now loading 21600 records. [*] Now loading 21700 records. [*] Now loading 21800 records. [*] Now loading 21900 records. [*] Now loading 22000 records. [*] Now loading 22100 records. [*] Now loading 22200 records. [*] Now loading 22300 records. [*] Now loading 22400 records. [*] Now loading 22500 records. [*] Now loading 22600 records. [*] Now loading 22700 records. [*] Now loading 22800 records. [*] Now loading 22900 records. [*] Now loading 23000 records. [*] Now loading 23100 records. [*] Now loading 23200 records. [*] Now loading 23300 records. [*] Now loading 23400 records. [*] Now loading 23500 records. [*] Now loading 23600 records. [*] Now loading 23700 records. [*] Now loading 23800 records. [*] Now loading 23900 records. [*] Now loading 24000 records. [*] Now loading 24100 records. [*] Now loading 24200 records. [*] Now loading 24300 records. [*] Now loading 24400 records. [*] Now loading 24500 records. [*] Now loading 24600 records. [*] Now loading 24700 records. [*] Now loading 24800 records. [*] Now loading 24900 records. [*] Now loading 25000 records. [*] Now loading 25100 records. [*] Now loading 25200 records. [*] Now loading 25300 records. [*] Now loading 25400 records. [*] Now loading 25500 records. [*] Now loading 25600 records. [*] Now loading 25700 records. [*] Now loading 25800 records. [*] Now loading 25900 records. [*] Now loading 26000 records. [*] Now loading 26100 records./usr/local/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead. from pandas.core import datetools logontracer.py:223: RuntimeWarning: Mean of empty slice. count_average = count_sum.mean(axis=0) [*] Load finished. [*] Total Event log is 26159. [*] Calculate PageRank. [*] Calculate ChangeFinder. [*] Creating a graph data. [*] Creation of a graph data finished. [*] Script end. 2018/05/31 08:05:12`

**Comment by shu-tom** [comment]
Does your EVTX file contain logon event IDs such as 4624, 4625, 4768, 4769 and 4776?
If the remote logon event log is not recorded in the EVTX file, LogonTracer does not display it.
