### ISSUE TITLE
Some missing steps in the install process - Gist inside

### ISSUE THREAD

**Issue by nepobef** [JPCERTCC/LogonTracer#2]
I got it successfully working installed onto a debian box, but I hit some snags that weren't covered.

I've written a [gist](https://gist.github.com/nepobef/0f378ded038b35324e0106fcff79303c) that should take people from a blank VM to a working install.

Feel free to include any steps in your project ;)

Nepobef

**Comment by shu-tom** [comment]
@nepobef  Thank you for your report!
I will create a wiki for LogonTracer based on your report.

**Comment by megamatman** [comment]
Above gist works well.  Thanks @nepobef

**Comment by shu-tom** [comment]
@nepobef  I created a [wiki](https://github.com/JPCERTCC/LogonTracer/wiki) based on your report. Thank you!

**Comment by kkomiyama** [comment]
Thanks @nepobef  for valuable feedback! We really appreciate it.
