### ISSUE TITLE
Parsing does not end

### ISSUE THREAD

**Issue by matftoledo** [JPCERTCC/LogonTracer#22]
Parsing does not end when the evtx file is imported, log indicates : 
 Now loading 30900 records.Traceback (most recent call last): File "logontracer.py", line 810, in main() File "logontracer.py", line 799, in main parse_evtx(args.evtx) File "logontracer.py", line 657, in parse_evtx tohours = int((endtime - starttime).total_seconds() / 3600) TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
But when import xml file, the process end succesfully.

**Comment by shu-tom** [comment]
Can you share the event log to me in order to resolve this issue?
If you can share it please send to logontracer.help (at) gmail.com

**Comment by DragonJAR** [comment]
I just happened the same, my evtx file is 21mb in size

> [*] Script start. 2018/07/10 21:57:10
> [*] Time zone is -5.
> [*] Last record number is 276700.
> [*] Start parsing the EVTX file.
> [*] Parse the EVTX file XXX.evtx.
> [*] Now loading 51900 records.Traceback (most recent call last):
>   File "logontracer.py", line 810, in <module>
>     main()
>   File "logontracer.py", line 799, in main
>     parse_evtx(args.evtx)
>   File "logontracer.py", line 657, in parse_evtx
>     tohours = int((endtime - starttime).total_seconds() / 3600)
> TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

**Comment by shu-tom** [comment]
Does your EVTX file contain logon event IDs such as 4624, 4625, 4768, 4769 and 4776?
If the remote logon event log is not recorded in the EVTX file, you get the error.
