### ISSUE TITLE
Evtx Import Error

### ISSUE THREAD

**Issue by hfakar** [JPCERTCC/LogonTracer#23]
This is what i am getting when i am trying to import evtx on Windows 10.

python logontracer.py --delete -e C:\windows\System32\Winevt\Logs\Security.evtx -z +2 -u neo4j -p password -s 127.0.0.1
[*] Script start. 2018/07/17 17:30:14
[*] Delete all nodes and relationships from this Neo4j database.
[*] Time zone is 2.
[*] Last record number is 4639937.
[*] Start parsing the EVTX file.
[*] Parse the EVTX file C:\windows\System32\Winevt\Logs\Security.evtx.
[*] Now loading 50600 records.
[*] Load finished.
[*] Total Event log is 50699.
[*] Calculate PageRank.
[*] Calculate ChangeFinder.
logontracer.py:308: RuntimeWarning: Mean of empty slice.
  count_average = count_sum.mean(axis=0)
C:\Python37\lib\site-packages\numpy\core\_methods.py:73: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
[*] Creating a graph data.
Traceback (most recent call last):
  File "logontracer.py", line 810, in <module>
    main()
  File "logontracer.py", line 799, in main
    parse_evtx(args.evtx)
  File "logontracer.py", line 730, in parse_evtx
    tx.append(statement_date, {"Daterange": "Daterange", "start": datetime.datetime(*starttime.timetuple()[:4]).strftime("%Y-%m-%d %H:%M:%S"),
AttributeError: 'Transaction' object has no attribute 'append'

**Comment by shu-tom** [comment]
This problem was caused by py2neo update imported by python script.
Please downgrade py2neo from v4 to 3.1.2.

**Comment by hfakar** [comment]
Thank you. It solved the problem. You may close the issue.
