### ISSUE TITLE
Localhost:8080

### ISSUE THREAD

**Issue by elmidwill** [JPCERTCC/LogonTracer#28]
When using Docker on Windows 10, trying to access localhost:8080 I receive:

This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by shu-tom** [comment]
It takes time to start LogonTracer. Please wait for about 40 seconds after starting the Docker image.

**Comment by elmidwill** [comment]
I have left it running for over a 5 minutes with the same result. I am running Windows 10 professional,1803, fully patched, latest docker. Are there logs somewhere I can provide?

**Comment by elmidwill** [comment]
I connected to the container, and ran netstat:

bash-4.3# netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:7687            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:7473            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:7474            0.0.0.0:*               LISTEN

Nothing is listening on port 8080, and what is 7473?

**Comment by elmidwill** [comment]
bash-4.3# ./run.sh
[!] Can't connect Neo4j Database.

**Comment by shu-tom** [comment]
Is the docker run command you used below?
```
$ docker run --detach --publish=7474:7474 --publish=7687:7687 --publish=8080:8080 -e LTHOSTNAME=127.0.0.1 jpcertcc/docker-logontracer
```

**Comment by elmidwill** [comment]
Docker novice move, did not enter the correct IP.

**Comment by NtHawk101** [comment]
I was seeing the same issue but changed to use the IP 127.0.0.1. I now see port 8080 show up in netstat as Listening with local address 0.0.0.0:8080 but I also see Time_Wait on 10.0.75.1:8080 and I never do get to the website as it appears the same as indicated above. I've been flipping between trying docker and Debian 9.5 and haven't been either to get to work yet
