### ISSUE TITLE
Which python3 version is recommanded?

### ISSUE THREAD

**Issue by jal-tw** [JPCERTCC/LogonTracer#29]
I tried many version of python, but all failed on different part.
3.7.0 failed on install hmmlearn
3.5.2 failed on numpy.dtype size changed, after uploaded EVTX file
3.5.0 failed on numpy.dtype size changed, after uploaded EVTX file
3.6.6 failed on numpy.dtype size changed, after uploaded EVTX file
RuntimeWarning: invalid value encountered in true_divide

So, have any suggested version of python?
Thanks.

**Comment by shu-tom** [comment]
I’m testing with Python 3.5.3 or lower.
The warning message numpy.dtype size changed of numpy seems to come out depending on the version of numpy.
Please check the following URL.
https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility/51587845
