### ISSUE TITLE
Launching logontracer.py fails (mac)

### ISSUE THREAD

**Issue by seajaysec** [JPCERTCC/LogonTracer#3]
Running the command in the setup guide fails. Not sure how to get past this. All steps prior went fine after I installed neo4j with brew.

`→ sudo python3 logontracer.py -r -o 8080 -u neo4j -p password -s 127.0.0.1`
`Traceback (most recent call last):`
 ` File "logontracer.py", line 70, in <module>`
   ` app = Flask(__name__)`
`NameError: name 'Flask' is not defined`

**Comment by shu-tom** [comment]
Have you installed Flask on Python3?
`pip3 install -r LogonTracer/requirements.txt`

**Comment by seajaysec** [comment]
Yes, and all requirements installed successfully. I tried following it up with `pip install flask` to double check but it's already installed.

**Comment by seajaysec** [comment]
@shu-tom I noticed that in your comment you said to use pip3 to install requirements, where the readme guide says to use pip. I just tried pip3 like you suggested and now I'm past that problem, with a different error.

`sudo python3 logontracer.py -r -o 8080 -u neo4j -p password -s 127.0.0.1`
`/usr/local/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.`
`from pandas.core import datetools`
`[!] Can't connect Neo4j Database.`

**Comment by shu-tom** [comment]
Did you change the default password of Neo4j?
Here is a more detail about installing LogonTracer, please refer to it.
[How to go from (almost) zero to viewing a graph of events with LogonTracer](https://gist.github.com/nepobef/0f378ded038b35324e0106fcff79303c)

**Comment by shu-tom** [comment]
Fixed exception handling when Flask is not installed. #5
