### ISSUE TITLE
Which license is used?

### ISSUE THREAD

**Issue by mboelen** [JPCERTCC/LogonTracer#30]
While [reviewing](https://linuxsecurity.expert/tools/logontracer/) LogonTracer for the security tools database, I could not find a license. Can you add one to the project?

**Comment by shu-tom** [comment]
Please refer to the LICENSE.txt in the https://github.com/JPCERTCC/LogonTracer/blob/master/LICENSE.txt

**Comment by mboelen** [comment]
Thanks for adding. I will update the review.
