### ISSUE TITLE
IPaddress:8080 fails to open

### ISSUE THREAD

**Issue by NtHawk101** [JPCERTCC/LogonTracer#31]
Since issue #25 was closed, I'm adding my issue here which is similar yet different. I also had set my IP address to the IP of the NAT address 10.0.75.1 and never saw port 8080 when running netstat. After changing to localhost:8080, I see 0.0.0.0:8080 as well as 10.0.75.1:8080 multiple times but in these were in TIME_WAIT status. I waited a couple hours and when I came back I still couldn't access the LogonTracer website. I re-ran netstat and while 0.0.0.0:8080 is still listening, then others at 10.0.75.1 have disappeared. When I try to access the webiste, I get the ERR_EMPTY_RESPONSE message in the browser.
Any thoughts or ideas would be most welcome at this point.

**Comment by shu-tom** [comment]
Is the docker run command you used below?

```
$ docker run --detach --publish=7474:7474 --publish=7687:7687 --publish=8080:8080 -e LTHOSTNAME=127.0.0.1 jpcertcc/docker-logontracer
```

**Comment by NtHawk101** [comment]
OK, I have this also working now. I had to connect to the URL of the Windows VM at http://[windows IP]:7474 and login and then change the password.
Once done, I then ran the command using the 127.0.0.1 IP and I could access the webpage at the NAT IP of 10.0.75.1:8080
