### ISSUE TITLE
hmmlearn must be installed for this script

### ISSUE THREAD

**Issue by NtHawk101** [JPCERTCC/LogonTracer#32]
Trying to install LogonTracer in Debian 9.5 adn having an issue when running the logontracer.py. My command is as follows:
python3 logontracer.py -r -o 8080 -u xxxx -p xxxx -s 127.0.0.1

One thing I've noticed is that there is no clear direction on where the git clone should be run from. I've installed to /etc/LogonTracer as well as the root /LogonTracer.

If I run the requirements.txt again, it states all are satisfied including hmmlearn.

What am I missing in this Debian install.

Thank you

**Comment by shu-tom** [comment]
The directory to execute git clone can be anywhere.
Please tell me error message when executing LogonTracer.

**Comment by NtHawk101** [comment]
The exact error is in the title. I found out that if I use Debian 9.2.1 that I don’t see this error and can get LogonTracer to run ok

Dave

On Aug 15, 2018, at 9:03 AM, shusei tomonaga <notifications@github.com<mailto:notifications@github.com>> wrote:


The directory to execute git clone can be anywhere.
Please tell me error message when executing LogonTracer.

**Comment by shu-tom** [comment]
Please tell me the version of Python you used.

**Comment by NtHawk101** [comment]
I used Debian 9.5

**Comment by shu-tom** [comment]
If you fail to install hmmlearn, please "pip3 install numpy" before "pip install -r requirements.txt"
