### ISSUE TITLE
Missing Events

### ISSUE THREAD

**Issue by Gizmo44z** [JPCERTCC/LogonTracer#33]
I am seeing events that aren't being parsed in the Security log.  One particular account lists >10,000 4625 events, but the graph does not capture any of those.  There were no errors in the log and it said "SUCCESSFUL" after parsing.  I have attached a scrubbed version of the log file we have seen this with, but there have been multiple files I have seen the same issue with.

I have tried uploading as EVTX and XML with no change in results.  Let me know if you need any additional details.

Thanks!
[Security_redacted.zip](https://github.com/JPCERTCC/LogonTracer/files/2295095/Security_redacted.zip)

**Comment by shu-tom** [comment]
Thank you for your event log.
I fixed a bug that ignored some events.

LogonTracer imports only remote logon events. For example, if IP address is ::1, it will not be imported. Many events in your event log will appear as local IP address.

**Comment by Gizmo44z** [comment]
Perfect!  Thanks for the info and update!
