### ISSUE TITLE
Event log import error

### ISSUE THREAD

**Issue by l1nk3rlin** [JPCERTCC/LogonTracer#34]
[*] Script start. 2018/08/22 15:58:12
[*] Delete all nodes and relationships from this Neo4j database.
[*] Time zone is 9.
[*] Last record number is 897.
[*] Start parsing the EVTX file.
[*] Parse the EVTX file /Users/l1nk3r/Desktop/3.evtx.
[*] Now loading 800 records.Traceback (most recent call last):
  File "logontracer.py", line 949, in <module>
    main()
  File "logontracer.py", line 938, in main
    parse_evtx(args.evtx)
  File "logontracer.py", line 779, in parse_evtx
    tohours = int((endtime - starttime).total_seconds() / 3600)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

**Comment by shu-tom** [comment]
The size of this log is small. Is the event ID related to remote logon recorded in this log? For example, 4624, 4768, 4769, 4776.
