### ISSUE TITLE
Event log parse error

### ISSUE THREAD

**Issue by ZheMoon** [JPCERTCC/LogonTracer#35]
I use some Log to test.Find one Log have error.give the result as follows:
`loading 28800 records./usr/local/src/LogonTracer/logontracer.py:327: RuntimeWarning: Mean of empty slice. count_average = count_sum.mean(axis=0) [*] Load finished. [*] Total Event log is 28881. [*] Calculate ChangeFinder. [*] Calculate Hidden Markov Model. [*] Calculate PageRank. Traceback (most recent call last): File "/usr/local/src/LogonTracer/logontracer.py", line 955, in main() File "/usr/local/src/LogonTracer/logontracer.py", line 944, in main parse_evtx(args.evtx) File "/usr/local/src/LogonTracer/logontracer.py", line 813, in parse_evtx ranks = pagerank(event_set, admins, detect_hmm, detect_cf, ntmlauth) File "/usr/local/src/LogonTracer/logontracer.py", line 405, in pagerank max_v = max(ranks.values()) ValueError: max() arg is an empty sequence`

Can you give a mail? I will give you the log of problem.

**Comment by shu-tom** [comment]
If you can share it please send to logontracer.help (at) gmail.com
