### ISSUE TITLE
MemoryError when importing large XML files (4GB+)

### ISSUE THREAD

**Issue by Rand1-1000** [JPCERTCC/LogonTracer#41]
Hi, 

When uploading large XML files we are getting a memory failure  when the file is startign to process itself. I checked if the python was 64bit and it was.  For references I attached the log file.

static/logontracer.log                                                                                        

[*] Script start. 2018/11/13 13:46:22
[*] Delete all nodes and relationships from this Neo4j database.
[*] Time zone is 1.
Traceback (most recent call last):
  File "/home/user/LogonTracer/logontracer.py", line 1022, in <module>
    main()
  File "/home/user/LogonTracer/logontracer.py", line 1016, in main
    parse_evtx(args.xmls)
  File "/home/user/LogonTracer/logontracer.py", line 616, in parse_evtx
    fb_data = fb.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
MemoryError

**Comment by shu-tom** [comment]
The solution to this issue is to add memory.

**Comment by Rand1-1000** [comment]
Hi,

Thank you for your feedback, could you please explain a bit deeper what you mean ?
I modified the VM to have 16GB of ram. I then studied the ram usage when the processing was being done and was 7GB max before the script stopped.

Kr,
Rand

**Comment by brandonstephens922** [comment]
I am experiencing the same issue. Has there been a resolution?

**Comment by shu-tom** [comment]
Fixed to reduce memory usage when loading XML files.
