### ISSUE TITLE
Transaction attribute error

### ISSUE THREAD

**Issue by sh13** [JPCERTCC/LogonTracer#45]
LogonTracer-master>python logontracer.py -e Security.evtx -z 5
[*] Script start. 2019/01/13 04:25:25
[*] Time zone is 5.
[*] Last record number is 11398.
[*] Start parsing the EVTX file.
[*] Parse the EVTX file Security.evtx.
[*] Now loading 11300 records.
[*] Load finished.
[*] Total Event log is 11398.
[*] Calculate ChangeFinder.
[*] Calculate Hidden Markov Model.
[*] Calculate PageRank.
[*] Creating a graph data.
Traceback (most recent call last):
  File "logontracer.py", line 1028, in <module>
    main()
  File "logontracer.py", line 1016, in main
    parse_evtx(args.evtx)
  File "logontracer.py", line 897, in parse_evtx
    tx.append(statement_ip, {"IP": ipaddress, "rank": ranks[ipaddress], "hostname": hostname})
AttributeError: 'Transaction' object has no attribute 'append'

Running the logontracer.py on anaconda prompt just gave me this error.Whats the solution to this?

**Comment by shu-tom** [comment]
What version of py2neo do you use?
Using py2neo v4 has problems. https://github.com/JPCERTCC/LogonTracer/issues/23

**Comment by sh13** [comment]
Version 4.1.3
