### ISSUE TITLE
Not working on Windows Server 2019 with docker and containers

### ISSUE THREAD

**Issue by EliWallic** [JPCERTCC/LogonTracer#46]
I installed docker as described here: https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server
After that i used - docker pull jpcertcc/docker-logontracer
and got the message: image operating system "linux" cannot be used on this platform

Should it work with windows as described in the wiki?

**Comment by shu-tom** [comment]
if you want to use Linux containers, make sure you enabled that mode

See this section in the documentation https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
