### ISSUE TITLE
Seems like cdn.rawgit.com is not hosting anymore.

### ISSUE THREAD

**Issue by paaff** [JPCERTCC/LogonTracer#47]
Hello!

I was trying out LogonTracer today, but kept these errors:

`ReferenceError: neo4j is not defined`

After looking at the source of `index.html` I noticed that the script source for the `neo4j` javascript driver was not up. 
Example of script source in index.html: https://github.com/JPCERTCC/LogonTracer/blob/master/templates/index.html#L19

Googling cdn.rawgit.com it seems like they are shutting down their service:
https://twitter.com/rawgit/status/1049360165030567937

I am pretty sure this is the cause of my issue. 

Thanks in advance and thanks for the cool tool! :+1:

**Comment by shu-tom** [comment]
Thank you for your good issue.
I changed js repository cdn.rawgit.com to cdn.jsdelivr.net.

**Comment by paaff** [comment]
Perfect!

I just cloned the updated version and it works flawlessly.

Thank you for the fast response and fix :)
