### ISSUE TITLE
WARNING: Search failed! error

### ISSUE THREAD

**Issue by windowsedrevents** [JPCERTCC/LogonTracer#48]
My upload was successful but I get only warning message if I click on any field like "All users" 

records. [*] Now loading 34200 records. [*] Now loading 34300 records. [*] Now loading 34400 records. [*] Now loading 34500 records. [*] Now loading 34600 records. [*] Now loading 34700 records. [*] Now loading 34800 records. [*] Now loading 34900 records. [*] Now loading 35000 records. [*] Now loading 35100 records. [*] Now loading 35200 records. [*] Now loading 35300 records. [*] Now loading 35400 records. [*] Now loading 35500 records. [*] Now loading 35600 records. [*] Now loading 35700 records. [*] Now loading 35800 records. [*] ### **Load finished.** [*] **Total Event log is 35898. [*] Calculate ChangeFinder. [*] Calculate Hidden Markov Model. [*] Calculate PageRank. [*] Creating a graph data. [*] Creation of a graph data finished. [*] Script end. 2019/04/01 10:53:26** 
![image](https://user-images.githubusercontent.com/46062215/55323215-09b03c00-54b1-11e9-8342-323f5ea77630.png)

**Comment by shu-tom** [comment]
Please write more details.
