### ISSUE TITLE
WARNING: Search failed!

### ISSUE THREAD

**Issue by Manoubi88** [JPCERTCC/LogonTracer#49]
I am using LogoTracer on Linux systems CentOS (Version 7.6.1810)  and Python 2.7.5.
I uploaded the evtx file in LogonTracer Web interface, after that I have the error: WARNING: Search failed!
But in the web interface of neo4j I can see the data of the evtx file (see image).
Log:
[*] Script start. 2019/05/01 12:00:18 
[*] Delete all nodes and relationships from this Neo4j database. 
[*] Time zone is 4. [*] Last record number is 34330. 
[*] Start parsing the EVTX file. 
[*] Parse the EVTX file /usr/local/src/LogonTracer/upload/0.evtx.
[*] Now loading 100 records.
.......
[*] Now loading 34300 records. 
[*] Load finished. 
[*] Total Event log is 34330.
[*] Calculate ChangeFinder. 
[*] Calculate Hidden Markov Model. 
[*] Calculate PageRank. 
[*] Creating a graph data. 
[*] Creation of a graph data finished. 
[*] Script end. 2019/05/01 12:12:32
![3](https://user-images.githubusercontent.com/48677488/57020539-d97fc880-6c29-11e9-8d99-f93cf5dad57a.jpg)
![2](https://user-images.githubusercontent.com/48677488/57020540-d97fc880-6c29-11e9-8714-3e39e03778a4.jpg)

**Comment by Manoubi88** [comment]
![3](https://user-images.githubusercontent.com/48677488/57020499-be14bd80-6c29-11e9-8193-4f418543e624.jpg)
![2](https://user-images.githubusercontent.com/48677488/57020500-bead5400-6c29-11e9-9a8d-d2a1cd8f56cf.jpg)

**Comment by shu-tom** [comment]
Please check the web browser console log.

**Comment by Manoubi88** [comment]
web browser console log:
![4](https://user-images.githubusercontent.com/48677488/57022390-49448200-6c2f-11e9-91e0-aab87f9ac9f3.jpg)

**Comment by shu-tom** [comment]
Please be able to connect to WebSocket from a web browser.

**Comment by Manoubi88** [comment]
Can you tell me please, how can I check it?

**Comment by Manoubi88** [comment]
WebSocket is already enabled in my browser

**Comment by shu-tom** [comment]
Did you allow access in Neo4j configuration?
https://github.com/JPCERTCC/LogonTracer/wiki/for-linux#change-neo4j-configuration-to-allow-remote-access

**Comment by Manoubi88** [comment]
Thank you, it's ok now, the problem was that the ports were closed.

**Comment by safebaseline** [comment]
> 
> 
> Thank you, it's ok now, the problem was that the ports were closed.

can you show me the detail?
