### ISSUE TITLE
Timeline Chart Colors Option Not Working

### ISSUE THREAD

**Issue by ionsor-zz** [JPCERTCC/LogonTracer#54]
The colors for anomaly detection score are not showing for the sample/Security.evtx
![image](https://user-images.githubusercontent.com/32057747/60507036-8678cf00-9cc7-11e9-8153-61be3ffb53e6.png)

**Comment by shu-tom** [comment]
The sample/Security.evtx is not anomaly detected because the count is low.

**Comment by ionsor-zz** [comment]
Is somewhere documented the defined threshold?

**Comment by shu-tom** [comment]
The changefinder anomaly threshold is 10.
