### ISSUE TITLE
Error SSL

### ISSUE THREAD

**Issue by famsedition** [JPCERTCC/LogonTracer#55]
Hello team jpcertcc, I am not able to connect to logon tracer pulled from docker.
In firefox i receive the following error :  SSL_ERROR_RX_RECORD_TOO_LONG
![image](https://user-images.githubusercontent.com/23343016/60668684-194a7280-9e5c-11e9-86f7-c7cbe535a212.png)

**Comment by shu-tom** [comment]
Please use http.

**Comment by famsedition** [comment]
@shu-tom I can't use http, it redirects to tomcat. see capture please
![image](https://user-images.githubusercontent.com/23343016/60720302-e1a20000-9f19-11e9-9962-754461c6e4a7.png)

**Comment by shu-tom** [comment]
LogonTracer docker does not use tomcat. You are accessing another system that is not LogonTracer.

**Comment by famsedition** [comment]
You right. It's was a conflictual tomcat installation.
Thanks
