### ISSUE TITLE
Timeline Chart Not Working

### ISSUE THREAD

**Issue by brandonstephens922** [JPCERTCC/LogonTracer#57]
I am having an issue with the timeline feature. It opens a new tab but there is no data. It is completely blank.

**Comment by shu-tom** [comment]
What web browser do you use? LogonTracer supported browsers are:
* Mozilla Firefox
* Google Chrome
* Microsoft Edge

https://github.com/JPCERTCC/LogonTracer/wiki/how-to-use#accessing-the-web-gui

**Comment by brandonstephens922** [comment]
I found the issue, user error of course. By default, no options are selected when the page opens therefore the page is blank. When I select the "All Users" button, the page is then populated.
