### ISSUE TITLE
WARNING: Search failed!

### ISSUE THREAD

**Issue by beru222** [JPCERTCC/LogonTracer#60]
## "WARNING: Search failed!" is displayed and not working.

* my browser Google Chrome. version: latest
* "DevTools" on chrome Console
`Edge `1261` has invalid endpoints and so it is impossible to draw.  Adjust your edge style (e.g. control points) accordingly or use an alternative edge type.  This is expected behaviour when the source node and the target node overlap.

cytoscape.min.js:23
`
What should I do?
Regards.

**Comment by shu-tom** [comment]
What search did you get this warning?

Can you share the event log to me in order to resolve this issue?
If you can share it please send to logontracer.help (at) gmail.com
