### ISSUE TITLE
py2neo 3.1.2 error in Python3.7

### ISSUE THREAD

**Issue by shu-tom** [JPCERTCC/LogonTracer#65]
I have completely removed neo4j from the system and reinstalled from a new package. All issues remain present. Please see output below:
python3 LogonTracer/logontracer.py -e testing3.evtx -z -4 -u neo4j -p ***** -s localhost
[*] Script start. 2019/11/14 08:30:47
[*] Time zone is -4.
[*] Last record number is 29748.
[*] Start parsing the EVTX file.
[*] Parse the EVTX file testing3.evtx.
[*] Now loading 29700 records.
[*] Load finished.
[*] Total Event log is 29748.
[*] Calculate ChangeFinder.
[*] Calculate Hidden Markov Model.
/home/uba9/.local/lib/python3.7/site-packages/hmmlearn/hmm.py:412: RuntimeWarning: divide by zero encountered in log
  return np.log(self.emissionprob_)[:, np.concatenate(X)].T
[*] Calculate PageRank.
[*] Creating a graph data.
LogonTracer/logontracer.py:956: DeprecationWarning: Transaction.append(...) is deprecated, use Transaction.run(...) instead
  tx.append(statement_ip, {"IP": ipaddress, "rank": ranks[ipaddress], "hostname": hostname})
LogonTracer/logontracer.py:989: DeprecationWarning: Transaction.append(...) is deprecated, use Transaction.run(...) instead
  "detect": ",".join(map(str, detects[i]))})
LogonTracer/logontracer.py:994: DeprecationWarning: Transaction.append(...) is deprecated, use Transaction.run(...) instead
  tx.append(statement_domain, {"domain": domain})
LogonTracer/logontracer.py:999: DeprecationWarning: Transaction.append(...) is deprecated, use Transaction.run(...) instead
  "status": events["status"], "count": events["count"], "authname": events["authname"], "date": events["date"]})
LogonTracer/logontracer.py:1003: DeprecationWarning: Transaction.append(...) is deprecated, use Transaction.run(...) instead
  tx.append(statement_dr, {"user": username[:-1], "domain": domain})
LogonTracer/logontracer.py:1007: DeprecationWarning: Transaction.append(...) is deprecated, use Transaction.run(...) instead
  "end": datetime.datetime(*endtime.timetuple()[:4]).strftime("%Y-%m-%d %H:%M:%S")})
[*] Creation of a graph data finished.
[*] Script end. 2019/11/14 08:35:00

Once again, there is data in the database but the LogonTracer:8080 page is unable to successfully run any searches.

_Originally posted by @brandonstephens922 in https://github.com/JPCERTCC/LogonTracer/issues/62#issuecomment-553892637_

**Comment by DarkWarrior0x** [comment]
I have the same error also and no one tries to answer me with a good answer

**Comment by shu-tom** [comment]
I fixed this issue. 0e038560b8dbbdacef523262f788e336cc9945c3
