### ISSUE TITLE
GUI | Parsing progress bar is not working

### ISSUE THREAD

**Issue by DarkWarrior0x** [JPCERTCC/LogonTracer#66]
![2019-11-19_12-12-10](https://user-images.githubusercontent.com/23270623/69137716-fa284680-0ac5-11ea-896d-76a1bf916cd6.jpg)

After the last update on the tool, the parsing progress bar that should appear after uploading the log now is stuck on uploading while the application is normally working.

This is not a bug, this is kinda a thing to make the application more better.
Also after finishing uploading and parsing there is nothing appeared on the GUI and still stuck on the uploading.

Also another thing i need a good tool to convert existing windows event logs .evtx to xml.

thanks a lot.

**Comment by shu-tom** [comment]
I fixed this issue. Please use a fixed version.
