### ISSUE TITLE
Q: multiple logs in one Logontracer instance

### ISSUE THREAD

**Issue by conventous** [JPCERTCC/LogonTracer#68]
Is Logontracer meant to visualise security logs from one machine at a time? Will uploading logs from multiple machines to one Logontracer instance without clearing database in between cause issues? We would like to visualise logs in one central location. I've done a small test (uploading two logs to one instance) without observing problems. However, I'd like confirmation on this question.

Thank you

**Comment by shu-tom** [comment]
We analyze multiple AD event logs with one LogonTracer instance.
