### ISSUE TITLE
Invalid timezone

### ISSUE THREAD

**Issue by ctmayhew** [JPCERTCC/LogonTracer#7]
Hi,

I always get invalid timezone when I select UTC.

> logontracer.py: error: argument -z/--timezone: invalid int value: 'UTC'

Is this a known issue? It works if you select 0 as the timezone.

**Comment by shu-tom** [comment]
When uploading an EVTX file, you need to set timezone from -12 to 14.
UTC does not work.

**Comment by shu-tom** [comment]
Removed UTC from Timezone select. f31c94d9ccbe1c95a6d33f6699ae75fa0538d389
