### ISSUE TITLE
Error when uploading XMLs generated by Logparser

### ISSUE THREAD

**Issue by blueteam0ps** [JPCERTCC/LogonTracer#73]
I used https://www.microsoft.com/en-au/download/details.aspx?id=24659  to convert EVTX to XMLs but LogonTracer throws an error when trying to upload. Is it not supported?

**Comment by shu-tom** [comment]
Yes, Log Parser is not supported.

**Comment by blueteam0ps** [comment]
What is your recommend parser to convert standalone security.evtx files obtained from isolated hosts?

**Comment by eljeffeg** [comment]
@zenmonk It looks like it supports an XML export from Event Viewer.
