### ISSUE TITLE
Dockerfile doesn't build, libssl1.0 no longer part of alpine 3.9

### ISSUE THREAD

**Issue by MikeHofmann** [JPCERTCC/LogonTracer#78]
libssl seems to be updated to v.1.1, so the Dockerfile no longer builds successful.

Maybe https://github.com/JPCERTCC/LogonTracer/blob/822aed69ee54e2e02cc3d763e84a4168f95aac17/docker/Dockerfile#L30 should be replaced with `libressl-dev` ?

**Comment by shu-tom** [comment]
Thanks. I update the Dockerfile.

**Comment by shu-tom** [comment]
Updated Dockerfile. 80473114a9bb4d1bc05a49db0b2b57a318c7f66e
