### ISSUE TITLE
Unable to import EVTX - list index out of range

### ISSUE THREAD

**Issue by TwtichVlad** [JPCERTCC/LogonTracer#8]
Hello

Currently having an issue where I am unable to import EVTX via either the web interface or by script.
I'm receiving the following error;
[*] Script start. 2018/01/30 16:39:53
[*] Time zone is 8.
Traceback (most recent call last):
  File "logontracer.py", line 526, in <module>
    main()
  File "logontracer.py", line 521, in main
    parse_evtx(args.evtx, GRAPH)
  File "logontracer.py", line 320, in parse_evtx
    last_chunk = list(evtx.chunks())[chunk]
IndexError: list index out of range

I have tried on two different systems with multiple evtx files, the installations are both fresh.

Thanks in advance.

**Comment by shu-tom** [comment]
Fixed a bug that can not import EVTX file. Please try the fixed version.
