### ISSUE TITLE
Error : "Can't get Neo4j kernel version" when uploading Event Log File

### ISSUE THREAD

**Issue by Bjonne** [JPCERTCC/LogonTracer#80]
Hi.

Installed following instuctions here : https://www.securitynik.com/2019/03/tracking-authentication-information.html
But I get "Can't get Neo4j kernel version" when I start LogonTracer or/and try to upload a event log file.

Version installed : 
neo4j/stable,now 1:3.5.14 all

![image](https://user-images.githubusercontent.com/67279994/85881217-8ed1f000-b7dd-11ea-90aa-3d80ac30b614.png)

Edit:Not sure LogonTracer is being maintained anymore. I see issues weeks ago that hasnt been commented on yet.

Thanks in advance for the help. 

Full log is here : 
Can't get Neo4j kernel version. Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 159, in _new_conn (self._dns_host, self.port), self.timeout, **extra_kw) File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 80, in create_connection raise err File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 70, in create_connection sock.connect(sa) ConnectionRefusedError: [Errno 111] Connection refused During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 600, in urlopen chunked=chunked) File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 354, in _make_request conn.request(method, url, **httplib_request_kw) File "/usr/lib/python3.6/http/client.py", line 1264, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/lib/python3.6/http/client.py", line 1310, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/lib/python3.6/http/client.py", line 1259, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/lib/python3.6/http/client.py", line 1038, in _send_output self.send(msg) File "/usr/lib/python3.6/http/client.py", line 976, in send self.connect() File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 181, in connect conn = self._new_conn() File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 168, in _new_conn self, "Failed to establish a new connection: %s" % e) urllib3.exceptions.NewConnectionError: : Failed to establish a new connection: [Errno 111] Connection refused During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/administrator/LogonTracer/logontracer.py", line 1203, in main() File "/home/administrator/LogonTracer/logontracer.py", line 1179, in main GRAPH.delete_all() File "/usr/local/lib/python3.6/dist-packages/py2neo/database.py", line 382, in delete_all self.run("MATCH (a) DETACH DELETE a") File "/usr/local/lib/python3.6/dist-packages/py2neo/database.py", line 533, in run return self.begin(autocommit=True).run(cypher, parameters, **kwparameters) File "/usr/local/lib/python3.6/dist-packages/py2neo/database.py", line 828, in run entities=entities)) File "/usr/local/lib/python3.6/dist-packages/py2neo/internal/connectors.py", line 369, in run r = self._post("/db/data/transaction/%s" % (tx or "commit"), statement, hydrator.dehydrate(parameters)) File "/usr/local/lib/python3.6/dist-packages/py2neo/internal/connectors.py", line 360, in _post body=json_dumps({"statements": statements})) File "/usr/local/lib/python3.6/dist-packages/urllib3/request.py", line 72, in request **urlopen_kw) File "/usr/local/lib/python3.6/dist-packages/urllib3/request.py", line 150, in request_encode_body return self.urlopen(method, url, **extra_kw) File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 667, in urlopen **response_kw) File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 667, in urlopen **response_kw) File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 667, in urlopen **response_kw) File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 638, in urlopen _stacktrace=sys.exc_info()[2]) File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 399, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=7474): Max retries exceeded with url: /db/data/transaction/commit (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by shu-tom** [comment]
LogonTracer shows this log when using the latest version of Neo4j, but there is no problem with that.

**Comment by freedom-wy** [comment]
`print("[+] Neo4j Kernel version: {0}".format(".".join(map(str, [db.kernel_start_time]))))`
