### ISSUE TITLE
This event log did not include logs to be visualized

### ISSUE THREAD

**Issue by xinbs** [JPCERTCC/LogonTracer#81]
records./usr/local/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead. import pandas.util.testing as tm [+] Load finished. [+] Total Event log is 1264348. [!] This event log did not include logs to be visualized. Please check the details of the event log.

**Comment by shu-tom** [comment]
This event log did not include logs to be visualized.
You need to import the AD security log.

**Comment by freedom-wy** [comment]
Active Directory log? @shu-tom
