### ISSUE TITLE
I can't see any any data.

### ISSUE THREAD

**Issue by yamamotoalex** [JPCERTCC/LogonTracer#85]
I promptly installed all packages and clone the logontracer, and I tried to upload evtx files and success. 
However I cannot see any graph at all. here is a log.

[root@logtracer-dc LogonTracer]# python3 logontracer.py -e /tmp/ad_security.evtx -z 9 -u neo4j -p hogehoge -s localhost
[+] Script start. 2020/08/12 18:50:58
[!] Can't get Neo4j kernel version.
[+] Time zone is 9.
[+] Last record number is 214327.
[+] Start parsing the EVTX file.
[+] Parse the EVTX file /tmp/ad_security.evtx.
[+] Now loading 214300 records.
[+] Load finished.
[+] Total Event log is 214327.
[+] Fildered Event log is 31709.
[+] Create cache files.
[+] Calculate ChangeFinder.
[+] Calculate Hidden Markov Model.
[+] Calculate PageRank.
[+] Creating a graph data.
[+] Creation of a graph data finished.
[+] Script end. 2020/08/12 19:25:12
[root@logtracer-dc LogonTracer]# python3 logontracer.py -r -o 8080 -u neo4j -p hogehoge -s localhost
[+] Script start. 2020/08/12 19:26:45
[!] Can't get Neo4j kernel version.
 * Serving Flask app "logontracer" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)

CentOS:7.5
neo4j 4.1.1
python 3.6

**Comment by shu-tom** [comment]
Please access to neo7j port 7474 and check the logs are saved. If it is ok, check the browser console log.

**Comment by yamamotoalex** [comment]
I confirmed that the log was entered correctly in the database via neo4j port 7474.

what does it mean about "browser console log" ? how can I check it ?

By the way, I intentionally ran the python script with the wrong password, but the result didn't change.
```
# python3 logontracer.py -r -o 8080 -u neo4j -p hoge -s localhost
[+] Script start. 2020/08/13 08:54:47
[!] Can't get Neo4j kernel version.
 * Serving Flask app "logontracer" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
```
Does it mean I cannot connect neo4j database with script?

**Comment by shu-tom** [comment]
Please check this:
https://www.google.com/search?q=how+to+view+chrome+console+log

**Comment by yamamotoalex** [comment]
Thank you, shu-tom for your support.
here is the logs.
```
Error:  Neo4jError: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3

    at https://cdn.jsdelivr.net/npm/neo4j-driver@4.1.1/lib/browser/neo4j-web.min.js:1:417958
    at new i (https://cdn.jsdelivr.net/npm/neo4j-driver@4.1.1/lib/browser/neo4j-web.min.js:1:418038)
    at a.value (https://cdn.jsdelivr.net/npm/neo4j-driver@4.1.1/lib/browser/neo4j-web.min.js:1:427232)
    at a.value (https://cdn.jsdelivr.net/npm/neo4j-driver@4.1.1/lib/browser/neo4j-web.min.js:1:426435)
    at pagerankQuery (http://aaa.bbb.ccc.218:8080/static/js/script.js:903:11)
    at http://aaa.bbb.ccc.218:8080/:330:5
```

**Comment by shu-tom** [comment]
Your browser cannot access Neo4j. Please check your neo4j configuration:
https://github.com/JPCERTCC/LogonTracer/wiki/for-linux#change-neo4j-configuration-to-allow-remote-access

**Comment by yamamotoalex** [comment]
I set the neo4j configuration below.
```
# Bolt connector
dbms.connector.bolt.enabled=true
#dbms.connector.bolt.tls_level=DISABLED
dbms.connector.bolt.listen_address=0.0.0.0:7687

# HTTP Connector. There can be zero or one HTTP connectors.
dbms.connector.http.enabled=true
dbms.connector.http.listen_address=0.0.0.0:7474
```
I can't find any doubts.

**Comment by yamamotoalex** [comment]
When I use the python script's option as real IP address, it does work !!
```
python3 logontracer.py -r -o 8080 -u neo4j -p hogehoge -s 10.20.30.40
```
when I use `-s localhost` , it doesn't work.
