### ISSUE TITLE
Converting EVTX to XML

### ISSUE THREAD

**Issue by blueteam0ps** [JPCERTCC/LogonTracer#86]
Your documentation says ""Supported file format is EVTX or XML (exported Event Viewer or PowerShell)".   I ran the following PS command to convert from EVTX to XML. However, the XML file which was generated doesn't work on Logontracer. Could you please recommend the command that does work ? Tx

Get-WinEvent -path .\file.evtx | Export-clixml -Encoding UTF8 output.xml

**Comment by shu-tom** [comment]
LogonTracer not support converting EVTX to XML with Powershell. Only Event viewer or wevtutil are supported.
https://github.com/JPCERTCC/LogonTracer/wiki/how-to-use#notes-for-import-evtx

**Comment by shu-tom** [comment]
LogonTracer parser for EVTX files is now faster. Please use the latest version.
