### ISSUE TITLE
logon?

### ISSUE THREAD

**Issue by y0d4a** [JPCERTCC/LogonTracer#9]
Hi, is there option to put some kind of login? i don`t want to be public avalaible ...

**Comment by shu-tom** [comment]
Could you please tell me a bit more about this issue. You do not need to logon to use LogonTracer.

**Comment by y0d4a** [comment]
there is no issue, just want to put some kind of login on him?
don`t want anyone to have access

**Comment by kkomiyama** [comment]
I am not sure logontracer itself should provide authentication, given there's various way to restrict the access to logontracer page. IMHO.

**Comment by y0d4a** [comment]
yeah, i know, just wanted to check is there plan for that, ok, thank you for your time and answer.
