### ISSUE TITLE
Docker Issue

### ISSUE THREAD

**Issue by ghost** [JPCERTCC/LogonTracer#94]
Good day.  

I have been trying to upload an EVTX file using the latest Docker image and the web GUI.  It states that it is at a 100% but it states it is still Parsing...
<img width="1146" alt="Screen Shot 2020-11-09 at 3 23 19 PM" src="https://user-images.githubusercontent.com/61256753/98592642-03469080-22a0-11eb-8a9a-6aba8eef18b2.png">

Any guidance would be appreciated.

Tim Craig

**Comment by ghost** [comment]
Also experiencing this issue!

**Comment by shu-tom** [comment]
It works fine in my docker. Please check the log.
