### ISSUE TITLE
many installation issues on Debian with python3.8+

### ISSUE THREAD

**Issue by JLT032** [JPCERTCC/LogonTracer#96]
Hello,

I hope you can help me to get this working, on Debian based Parrot Linux many issues when installing.

what i found required was

`apt install libmkl-rt`

what partially worked for me

  apt remove python3-scipy python3-numpy
  pip3 install scipy numpy

The list of warnings and error messages is extensive so i do not post everything here.

    gfortran:f77: /tmp/pip-install-pz8frrlu/scipy_5f39eb0ee48e4951aefba6a45891513a/scipy/_build_utils/src/wrap_g77_abi_f.f
    error: Command "/usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops -Iscipy/sparse/linalg/eigen/arpack/ARPACK/SRC -I/usr/lib/python3/dist-packages/numpy/core/include -c -c scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaup2.f -o build/temp.linux-x86_64-3.9/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaup2.o" failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of scipy
  Moving to /usr/lib/python3/dist-packages/scipy
   from /usr/lib/python3/dist-packages/~cipy
  Moving to /usr/lib/python3/dist-packages/scipy-1.5.4.egg-info
   from /usr/lib/python3/dist-packages/~cipy-1.5.4.egg-info
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pz8frrlu/scipy_5f39eb0ee48e4951aefba6a45891513a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pz8frrlu/scipy_5f39eb0ee48e4951aefba6a45891513a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tmmxfdbz/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/scipy Check the logs for full command output.

**Comment by t-tani** [comment]
From your log, it shows that the compile process of Scipy with Fortran is failing. This error is out of scope for LogonTracer.
If you couldn't solve this Scipy install error, please use the environment Scipy works or Docker image.
